name: Canary build
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-binaries:
    name: build binaries
    uses: ./.github/workflows/build.yaml
    with:
      goreleaser_file: goreleaser-canary.yml
      goreleaser_options: '--snapshot --rm-dist --timeout 60m'

  upload-binaries:
    name: upload-binaries
    needs: build-binaries # run this jobs afterbuild-binaries job completes
    runs-on: ubuntu-18.04 # 20.04 doesn't provide createrepo for now
    steps:
      - name: Restore Trivy binaries from cache
        uses: actions/cache@v3.0.2
        with:
          path: dist/
          key: ${{ runner.os }}-bins-${{github.workflow}}-${{github.sha}}

        # Upload artifacts
      - name: Upload artifacts (trivy_Linux-64bit)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_Linux-64bit
          path: dist/trivy_*_Linux-64bit.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_Linux-ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_Linux-ARM64
          path: dist/trivy_*_Linux-ARM64.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_macOS-64bit)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_macOS-64bit
          path: dist/trivy_*_macOS-64bit.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_macOS-ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_macOS-ARM64
          path: dist/trivy_*_macOS-ARM64.tar.gz
          if-no-files-found: error