name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            BREAKING

          scopes:
            vuln
            misconf
            secret

            image
            fs
            repo
            sbom
            server

            alpine
            redhat
            alma
            rocky
            mariner
            oracle
            debian
            ubuntu
            amazon
            suse
            photon
            distroless

            ruby
            php
            python
            nodejs
            rust
            dotnet
            java
            go
            
            os
            lang

            kubernetes
            dockerfile
            terraform
            cloudformation

            docker
            podman
            containerd
            oci

            cli
            flag

            helm
            report
            db
            deps