name: "Stale PR's"
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stale:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been labeled with inactivity.'
        exempt-pr-labels: 'lifecycle/active'
        stale-pr-label: 'lifecycle/stale'
        days-before-stale: 60
        days-before-issue-stale: '-1'
        days-before-close: 20
        days-before-issue-close: '-1'
