name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days'
        days-before-stale: 30
        days-before-close: 30
        stale-issue-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/active,lifecycle/frozen,priority/critical-urgent,priority/important-soon,priority/important-longterm,priority/backlog'
